name: fast CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
    -  '.gitignore'
    -  '.dockerignore'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -uses:  actions/checkout@v4
       with:
         fetch-depth: 1
